version: "3"
services:
    cement: &DEFAULTS
        image: "cement:dev"
        build:
            context: .
            dockerfile: docker/Dockerfile.dev
        hostname: cement
        stdin_open: true
        tty: true
        volumes:
            - '.:/src'
        working_dir: '/src'
        links:
            - redis:redis
            - memcached:memcached
        environment:
            REDIS_HOST: redis
            MEMCACHED_HOST: memcached

    cement-py35:
        <<: *DEFAULTS
        image: "cement:dev-py35"
        build:
            context: .
            dockerfile: docker/Dockerfile.dev-py35

    cement-py36:
        image: "cement:dev-py36"
        build:
            context: .
            dockerfile: docker/Dockerfile.dev-py36
        <<: *DEFAULTS

    cement-py37:
        image: "cement:dev-py37"
        build:
            context: .
            dockerfile: docker/Dockerfile.dev-py37
        <<: *DEFAULTS
    
    cement-py38:
        image: "cement:dev-py38"
        build:
            context: .
            dockerfile: docker/Dockerfile.dev-py38
        <<: *DEFAULTS

    redis:
        image: redis:latest
        hostname: redis

    memcached:
        image: memcached:latest
        hostname: memcached
